# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ["develop"]
    paths:
      - "workspaces/cube-clarity-front/**"
  pull_request:
    branches: ["develop"]
    paths:
      - "workspaces/cube-clarity-front/**"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@v2  # v1.1.2
        with:
          deno-version: v2.x

      # - name: install dependencies
      #   run: deno install

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      - name: Verify formatting
        run: deno task --filter @cube-clarity/front fmt:check

      # - name: Run server code type check
      #   run: deno task --filter @cube-clarity/front fmt:check
